### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by Tatsuto-Hatanaka** [lan496/crystal-symmetry-primer#1]
* (p.5)...the metric tensor **are** changed...<br> -> the metric tensor **is** changed...
* (p.6)...we fix some **orgin** O and... <br> -> we fix some **origin** O and...
* (p.8)...the lattice spanned the basis vectors... <br> -> the lattice spanned **by** the basis vectors...
* (p.9) The last matrix in the $pm$ and $cm$ case does not correspond correctly to FIg. 1. Aren't the $x$-axis and $y$-axis reversed?

**Comment by lan496** [comment]
@Tatsuto-Hatanaka Thanks for your report! I've fixed them at https://github.com/lan496/crystal-symmetry-primer/commit/6cdcb529a211183eb15b5443414251c92206bd9b.

> (p.9) The last matrix in the pm and cm case does not correspond correctly to FIg. 1. Aren't the x-axis and y-axis reversed?

Diagrams in Fig.1 are adapted from International Table Vol. A (ITA). ITA chooses $a$ axis to run from top to bottom and $b$ axis to run from left to right. Thus, this figure will be correct although it may not be an intuitive setting...
